apiVersion: v1
kind: Service
metadata:
  name: pes2ug23cs062-service
  namespace: pes2ug23cs062-beta
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80